/// Flutter icons FlatIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlatIcon
///      fonts:
///       - asset: fonts/FlatIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FlatIcon1 {
  FlatIcon1._();

  static const _kFontFam = 'FlatIconNew1';
  static const String? _kFontPkg = 'html_editor_enhanced';

  static const IconData bold = IconData(0xf101, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strikethrough = IconData(0xf102, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic = IconData(0xf103, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number = IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullet_list = IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left = IconData(0xf107, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xf108, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_center = IconData(0xf109, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xf10a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right = IconData(0xf10b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData justification = IconData(0xf10c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
